language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose
  - cargo test --verbose
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
